# Generated by Django 5.2.5 on 2026-09-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_centers',
            field=models.TextField(blank=True, default='IVAC Khulna\nIVAC CTG\nIVAC Dhaka (JFP)\nIVAC Rajshahi\nIVAC Sylhet', help_text='One center per line'),
        ),
        migrations.AddField(
            model_name='service',
            name='slot_rates',
            field=models.TextField(blank=True, default='IVAC Dhaka (JFP): 4500 TK\nIVAC Khulna: 6000 TK', help_text='One rate per line, example: IVAC Dhaka (JFP): 4500 TK'),
        ),
    ]
