# Generated by Django 5.2.5 on 2026-09-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_available_centers_service_slot_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='House 70, Road 11, Block D, Banani, Dhaka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='agency_name',
            field=models.CharField(default='Nasir Travel & Consultancy', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_phone',
            field=models.CharField(blank=True, default='+8801620-855800', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(blank=True, default='Sun-Thu : 9:00 AM - 8:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 Nasir Travel & Consultancy. All Rights Reserved.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='travelnasir91@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about_text',
            field=models.TextField(default='We provide fast, reliable, and hassle-free visa, ticket, tour, and travel support services with trusted professional guidance.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Fast, reliable, and hassle-free visa and travel support services across all countries with Nasir Travel & Consultancy.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='Nasir Travel & Consultancy | Visa & Travel Solutions', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+8801762364249', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Nasir Travel & Consultancy', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Your Journey | Our Priority', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='+8801762364249', help_text='Full number with country code, no spaces. e.g. +8801812345678', max_length=30),
        ),
    ]
